version: "3.8"

services:
  demo-spring-boot-service:
    image: thappatan/demo-spring-boot:0.0.2
    container_name: demo-spring-boot-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    