pipeline{
    agent any

    stages{
        stage('run test'){
            steps{
                sh label: 'run test', script: '''
                cd demo-spring-boot-gradle
                ./gradlew clean test
                '''
            }
        }
        stage('run coverage report with Jacoco'){
            steps{
                sh label: 'report test', script: '''
                cd demo-spring-boot-gradle
                ./gradlew jacocoTestReport
                '''
            }
        }
        stage('build'){
            steps{
                sh label: 'build application', script: '''
                cd demo-spring-boot-gradle
                ./gradlew build'''
            }
        }
        stage('start application'){
            steps{
                sh label: 'start application', script: '''
                cd demo-spring-boot-gradle
                java -jar ./build/libs/demo-spring-boot-gradle-0.0.1-SNAPSHOT.jar
                '''
            }
            post {
                always {
                    jacoco execPattern: 'build/jacoco/test.exec'
                }
            }
        }
    }
}